### ISSUE TITLE
CPU와 GPU 모델 불러오기 과정에서 오류

### ISSUE THREAD

**Issue by gregchu1** [VHEX-LAB/VHEX-Tech#10]
![20210625165601](https://user-images.githubusercontent.com/37770967/123390960-748c4700-d5d6-11eb-9426-26152038cb7b.png)
![20210625165614](https://user-images.githubusercontent.com/37770967/123390961-7524dd80-d5d6-11eb-90dc-0bf972ef4bce.png)

**SOLUTION**
PATH에서 추가 인자로 map_loacation=device 추가해주기
![20210625165813](https://user-images.githubusercontent.com/37770967/123391032-8968da80-d5d6-11eb-9d68-ef53f5e83829.png)

**Comment by songhune** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [7월 5주차](https://trello.com/c/iyDni7wj/210-7%EC%9B%94-5%EC%A3%BC%EC%B0%A8)
