### ISSUE TITLE
서버 접속 & 주피터 노트북 & repo cloning

### ISSUE THREAD

**Issue by songhune** [VHEX-LAB/VHEX-Tech#5]
NIPA 드라이브 활용할 수 있게끔 서버 셋팅하고
GAN프로젝트 준비해 주시면 좋겠습니다.

**Comment by songhune** [comment]
서버접속 완료, GAN프로젝트 올리기 전에, 해당 파일에 본인 계정 만들어 놓으시기 바랍니다.

**Comment by YoungJSim** [comment]
N#S-=iB9{:CKi6.    이거로 로그인하려는데
![image](https://user-images.githubusercontent.com/50852493/123387373-ae5b4e80-d5d2-11eb-8853-90d7874f8da5.png)
계속 접속이 안됩니다
