### ISSUE TITLE
RuntimeError: GPU driver / version conflict between PyTorch and CUDA driver

### ISSUE THREAD

**Issue by gregchu1** [VHEX-LAB/VHEX-Tech#9]
![20210625150955](https://user-images.githubusercontent.com/37770967/123378932-57507c00-d5c8-11eb-99e7-95e9b272962d.png)

cuda 관련 부분의 코드를 실행하면
![20210625151016](https://user-images.githubusercontent.com/37770967/123378973-62a3a780-d5c8-11eb-8c17-1698e01a393c.png)
GPU 드라이버 업그레이드 하거나 CUDA 드라이버에 맞게 pytorch 깔라고 함

**Comment by gregchu1** [comment]
![20210625151628](https://user-images.githubusercontent.com/37770967/123381011-1e65d680-d5cb-11eb-8fde-bcd6a27fb6a1.png)
![20210625151548](https://user-images.githubusercontent.com/37770967/123381013-1efe6d00-d5cb-11eb-9d4c-fbc990c3aecc.png)
![20210625152058](https://user-images.githubusercontent.com/37770967/123381034-27ef3e80-d5cb-11eb-9d74-a463d205b03a.png)

GPU 드라이버 업그레이드는 안 됨

**Comment by gregchu1** [comment]
Torch 1.8.1 + Cuda 11.1 버전으로 재설치
명령어 : pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html

**Comment by songhune** [comment]
Cpu로 코드 바꾸시면 됩니다

**Comment by gregchu1** [comment]
관리자 모드에서 재설치해도 액세스 거부 발생
![20210625155320](https://user-images.githubusercontent.com/37770967/123382921-79003200-d5cd-11eb-8fda-067850b0670f.png)

이후 코드 재실행시 CUDA gpu 필요하다고 함
![20210625155255](https://user-images.githubusercontent.com/37770967/123382878-6b4aac80-d5cd-11eb-91b7-48bd2bd2228a.png)

GPU 안 좋아서 그런듯 / CPU 버전으로 재설치
![20210625155458](https://user-images.githubusercontent.com/37770967/123383094-b4026580-d5cd-11eb-8b33-0b16412dad27.png)

CPU 버전 설치도 막힘
![20210625155734](https://user-images.githubusercontent.com/37770967/123383386-10658500-d5ce-11eb-9bf7-9ae00cd8d5e7.png)

→ torch.device에서 cpu로 변경
![20210625160307](https://user-images.githubusercontent.com/37770967/123384030-d8127680-d5ce-11eb-940b-499311613af8.png)

해결 완료

**Comment by songhune** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [7월 5주차](https://trello.com/c/iyDni7wj/210-7%EC%9B%94-5%EC%A3%BC%EC%B0%A8)
